//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmMonitor.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarm_record
    {
        public int id { get; set; }
        public Nullable<int> node_id { get; set; }
        public string line { get; set; }
        public Nullable<int> status { get; set; }
        public string pause_type { get; set; }
        public Nullable<System.DateTime> pause_time { get; set; }
        public Nullable<System.DateTime> recover_time { get; set; }
        public Nullable<int> upload { get; set; }
    }
}
