//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmMonitor.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT_LOG
    {
        public Nullable<System.DateTime> timestamp { get; set; }
        public System.DateTime timestamp_utc { get; set; }
        public int sequence_number { get; set; }
        public string alarm_id { get; set; }
        public string alarm_class { get; set; }
        public string resource { get; set; }
        public string logged_by { get; set; }
        public string reference { get; set; }
        public string alarm_message { get; set; }
        public Nullable<System.DateTime> generation_time { get; set; }
        public Nullable<System.DateTime> generation_time_utc { get; set; }
    }
}
