//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmMonitor.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class station_info
    {
        public string ID { get; set; }
        public string ALARM_ID { get; set; }
        public string ALARM_MESSAGE { get; set; }
        public string STATION { get; set; }
        public string POSITION { get; set; }
        public Nullable<int> PNODE_ID { get; set; }
    }
}
