//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmMonitor.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_log
    {
        public int ID { get; set; }
        public string UName { get; set; }
        public string UID { get; set; }
        public string PWD { get; set; }
        public Nullable<System.DateTime> LogInTime { get; set; }
    }
}
